In [3]:
# Uso de numpy
import numpy as np

In [5]:
x = np.arange(12)

In [7]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
x = x.reshape(4,3)

In [13]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
z= np.identity(5)

In [19]:
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
y = np.array([[10,20,30], [40,50,60], [70,80,90]])

In [23]:
print(y)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
import pandas as pd

In [31]:
data=pd.read_csv('tiburon.csv', index_col=0)

In [33]:
print(data)

      year        type             country        activity  age  \
0     2018     Boating                 usa        Paddling   57   
1     2018  Unprovoked              brazil        Swimming   18   
2     2018  Unprovoked                 usa         Walking   15   
3     2018    Provoked           australia  Feeding sharks   32   
4     2018     Invalid             england         Fishing   21   
...    ...         ...                 ...             ...  ...   
1667     0  Unprovoked           australia          Diving  NaN   
1668     0  Unprovoked           australia    Pearl diving  NaN   
1669     0  Unprovoked                 usa        Swimming  NaN   
1670     0  Unprovoked              panama             NaN  NaN   
1671     0  Unprovoked  ceylon (sri lanka)        Swimming   15   

               species month fatal gender  
0          White shark   Jun     N      F  
1          Tiger shark   Jun     Y      M  
2       Bull shark, 6'   May     N      M  
3      Grey reef sh

In [35]:
data.head()

year        type    country        activity age           species month  \
0  2018     Boating        usa        Paddling  57       White shark   Jun   
1  2018  Unprovoked     brazil        Swimming  18       Tiger shark   Jun   
2  2018  Unprovoked        usa         Walking  15    Bull shark, 6'   May   
3  2018    Provoked  australia  Feeding sharks  32   Grey reef shark   May   
4  2018     Invalid    england         Fishing  21  Invalid incident   May   

  fatal gender  
0     N      F  
1     Y      M  
2     N      M  
3     N      M  
4     N      M

In [37]:
data.tail()

year        type             country      activity  age species month  \
1667     0  Unprovoked           australia        Diving  NaN     NaN   NaN   
1668     0  Unprovoked           australia  Pearl diving  NaN     NaN   NaN   
1669     0  Unprovoked                 usa      Swimming  NaN     NaN   NaN   
1670     0  Unprovoked              panama           NaN  NaN     NaN   NaN   
1671     0  Unprovoked  ceylon (sri lanka)      Swimming   15     NaN   NaN   

     fatal gender  
1667     Y      M  
1668     Y      M  
1669     Y      M  
1670     Y      M  
1671     Y      M

In [39]:
data.head(1)

year     type country  activity age      species month fatal gender
0  2018  Boating     usa  Paddling  57  White shark   Jun     N      F

In [41]:
data.tail(1)

year        type             country  activity age species month fatal  \
1671     0  Unprovoked  ceylon (sri lanka)  Swimming  15     NaN   NaN     Y   

     gender  
1671      M

In [43]:
data.columns

Index(['year', 'type', 'country', 'activity', 'age', 'species', 'month',
       'fatal', 'gender'],
      dtype='object')

In [45]:
data.dtypes

year         int64
type        object
country     object
activity    object
age         object
species     object
month       object
fatal       object
gender      object
dtype: object

In [47]:
data.shape

(1669, 9)

In [49]:
data.size

15021

In [51]:
data_copy = data.copy()

In [53]:
data_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1669 entries, 0 to 1671
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   year      1669 non-null   int64 
 1   type      1669 non-null   object
 2   country   1659 non-null   object
 3   activity  1638 non-null   object
 4   age       1517 non-null   object
 5   species   1544 non-null   object
 6   month     1517 non-null   object
 7   fatal     1570 non-null   object
 8   gender    1655 non-null   object
dtypes: int64(1), object(8)
memory usage: 130.4+ KB


In [55]:
data_duplicados = data_copy.duplicated()

In [57]:
print(data_duplicados)

0       False
1       False
2       False
3       False
4       False
        ...  
1667    False
1668    False
1669    False
1670    False
1671    False
Length: 1669, dtype: bool


In [67]:
data_copy['month'] = data_copy['month'].fillna('Unknow')

In [69]:
data_copy['species'] = data_copy['species'].fillna('Unknow')

In [71]:
data_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1669 entries, 0 to 1671
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   year      1669 non-null   int64 
 1   type      1669 non-null   object
 2   country   1659 non-null   object
 3   activity  1638 non-null   object
 4   age       1517 non-null   object
 5   species   1669 non-null   object
 6   month     1669 non-null   object
 7   fatal     1570 non-null   object
 8   gender    1655 non-null   object
dtypes: int64(1), object(8)
memory usage: 130.4+ KB
